/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chawp
 */
public class ALU extends javax.swing.JFrame {

    /**
     * Creates new form ALU
     */
    public ALU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        operation = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextPane();
        resetSet = new javax.swing.JCheckBox();
        addSet = new javax.swing.JCheckBox();
        multSet = new javax.swing.JCheckBox();
        andSet = new javax.swing.JCheckBox();
        subSet = new javax.swing.JCheckBox();
        orSet = new javax.swing.JCheckBox();
        xorSet = new javax.swing.JCheckBox();
        notSet = new javax.swing.JCheckBox();
        loadSet = new javax.swing.JCheckBox();
        reset2Set = new javax.swing.JCheckBox();
        onSet = new javax.swing.JCheckBox();
        offSet = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextPane();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        input.setAutoscrolls(false);
        jScrollPane1.setViewportView(input);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 147, 33);

        resetSet.setText("RST");
        resetSet.setToolTipText("");
        resetSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSetActionPerformed(evt);
            }
        });
        getContentPane().add(resetSet);
        resetSet.setBounds(410, 520, 60, 23);

        addSet.setText("ADD");
        addSet.setToolTipText("");
        getContentPane().add(addSet);
        addSet.setBounds(410, 580, 47, 23);

        multSet.setText("MULT");
        multSet.setToolTipText("");
        getContentPane().add(multSet);
        multSet.setBounds(410, 550, 60, 23);

        andSet.setText("AND");
        andSet.setToolTipText("");
        getContentPane().add(andSet);
        andSet.setBounds(410, 640, 47, 23);

        subSet.setText("SUB");
        subSet.setToolTipText("");
        getContentPane().add(subSet);
        subSet.setBounds(410, 610, 50, 23);

        orSet.setText("OR");
        orSet.setToolTipText("");
        getContentPane().add(orSet);
        orSet.setBounds(410, 670, 41, 23);

        xorSet.setText("XOR");
        xorSet.setToolTipText("");
        getContentPane().add(xorSet);
        xorSet.setBounds(410, 700, 47, 23);

        notSet.setText("NOT");
        notSet.setToolTipText("");
        getContentPane().add(notSet);
        notSet.setBounds(410, 730, 47, 23);

        loadSet.setText("LOAD");
        loadSet.setToolTipText("");
        getContentPane().add(loadSet);
        loadSet.setBounds(410, 760, 60, 23);

        reset2Set.setText("RST");
        reset2Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2SetActionPerformed(evt);
            }
        });
        getContentPane().add(reset2Set);
        reset2Set.setBounds(90, 990, 60, 23);

        onSet.setText("ON");
        getContentPane().add(onSet);
        onSet.setBounds(90, 1020, 60, 23);

        offSet.setText("OFF");
        getContentPane().add(offSet);
        offSet.setBounds(90, 1050, 45, 23);

        output.setEditable(false);
        output.setAutoscrolls(false);
        jScrollPane2.setViewportView(output);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1060, 180, 137, 33);

        inputLabel.setText("Input");
        getContentPane().add(inputLabel);
        inputLabel.setBounds(30, 170, 26, 14);

        outputLabel.setText("Output");
        getContentPane().add(outputLabel);
        outputLabel.setBounds(1070, 160, 40, 14);

        goButton.setText("I'M READY");
        getContentPane().add(goButton);
        goButton.setBounds(40, 250, 90, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ALU temp.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -470, 1530, 2030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSetActionPerformed
        //reset is the same input wire, so if one is set the other is too
        if(resetSet.isSelected())
            reset2Set.setSelected(true);
        else if(!resetSet.isSelected())
            reset2Set.setSelected(false);
    }//GEN-LAST:event_resetSetActionPerformed

    private void reset2SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2SetActionPerformed
        //reset is the same input wire, so if one is set the other is too
        if(reset2Set.isSelected())
            resetSet.setSelected(true);
        else if(!reset2Set.isSelected())
            resetSet.setSelected(false);
    }//GEN-LAST:event_reset2SetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALU().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addSet;
    private javax.swing.JCheckBox andSet;
    private javax.swing.JButton goButton;
    private javax.swing.JTextPane input;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox loadSet;
    private javax.swing.JCheckBox multSet;
    private javax.swing.JCheckBox notSet;
    private javax.swing.JCheckBox offSet;
    private javax.swing.JCheckBox onSet;
    private javax.swing.ButtonGroup operation;
    private javax.swing.JCheckBox orSet;
    private javax.swing.JTextPane output;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JCheckBox reset2Set;
    private javax.swing.JCheckBox resetSet;
    private javax.swing.JCheckBox subSet;
    private javax.swing.JCheckBox xorSet;
    // End of variables declaration//GEN-END:variables
}
